### ISSUE TITLE
Any plan on create a demo site with matchering?

### ISSUE THREAD

**Issue by yoyololicon** [sergree/matchering#12]
Thanks for your hard working on containerize the whole project !
I want to say congrats to everyone who have participated in it, thank you :clap: 
I would also like to ask is there any plan on create a demo site so everyone can access the serverce ?

BTW I have run it on a private docker server and it works well, but the loading time is a little bit long though (~= 10 seconds).

**Comment by sergree** [comment]
@yoyololicon 

Thank you so much for your help, too! ☀

> I would also like to ask is there any plan on create a demo site so everyone can access the serverce ?

I have no such plan. Due to the fact that the web application must receive and serve large (audio) files, this creates some difficulties and pitfalls. My colleague and I were not able to solve them all in 2017-2018, which is why our online service was closed. I described some of them on [this page](https://github.com/sergree/matchering/wiki/Keep-the-Privacy). And [here](https://github.com/sergree/matchering/blob/master/THOUGHTS.md). I just don't have the proper knowledge, time, and money to do this. 

But again, I think my containerized web app is perfect for home and internal use. 🏠

It may not be too easy to install for the end user, but it's worth the effort. I think. 🆓 🔓

I don't mind if someone makes a proper public online service using our library, I will only be happy.

> BTW I have run it on a private docker server and it works well, but the loading time is a little bit long though (~= 10 seconds).

I think it depends on the processor of your server. But 10 seconds is normal, I think.

I have added a few ideas to [this page](https://github.com/sergree/matchering/projects/2) that can be implemented in the future at a more relaxed pace.

**Comment by yoyololicon** [comment]
I see, that's a fair reason.

**Comment by GoodnessEzeokafor** [comment]
also a tutorial on how to use matchering to django and how to save the mastered tracks to a db

**Comment by sergree** [comment]
@GoodnessEzeokafor 
https://github.com/sergree/matchering-web

This is not a tutorial, but a ready Django solution for home & in-house use

**Comment by GoodnessEzeokafor** [comment]
ok nice

**Comment by sergree** [comment]
Everyone can use Matchering at [Moises.ai](https://moises.ai) now.
