### ISSUE TITLE
mono vs stereo output

### ISSUE THREAD

**Issue by RoyJames** [sergree/matchering#42]
Hi,

Great repo! Just had one question: when both target and reference are stereo I think everything makes sense. But if both of them are mono, current code converts the target to stereo on loading by duplicating its channel. After all the matching process, the output is a stereo file containing two identical channels, which is essentially mono. Would there be any issue if we don't convert the input/target to stereo in the beginning?

Thanks,
Zhenyu

**Comment by sergree** [comment]
Hey, Zhenyu!
Current matchering can only handle stereo internally.
In any case, it will try to calculate the mid and side channels, even if the target / reference audio was previously in mono.

Basically, this step will fail:
https://github.com/sergree/matchering/blob/a05b1a8f429222b9179f3d476e6488a1b5915e31/matchering/stage_helpers/match_levels.py#L139

Because the code assumes that there are exactly 2 channels:
https://github.com/sergree/matchering/blob/a05b1a8f429222b9179f3d476e6488a1b5915e31/matchering/dsp.py#L57-L64

**Comment by sergree** [comment]
And of course thank you for your kind words, @RoyJames.
They inspire. 😇

**Comment by RoyJames** [comment]
Thank you for the explanation. I'll do some changes on its output then.
